name: analyzer_buffer
version: 0.1.11
description: A package to help writing code-generators while supporting import prefixes and default values
repository: https://github.com/rrousselGit/analyzer_buffer

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  collection: ^1.19.1
  meta: ^1.15.0
  path: ^1.9.1
  source_gen: ^4.0.0

dev_dependencies:
  test: ^1.25.15
