name: flutter_markdown_example
description: Demonstrates how to use the flutter_markdown_plus package.
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_markdown_plus: ^1.0.3

  flutter_markdown_plus:
    path: ../
#  flutter_markdown_plus_latex:
#    path: ../../flutter_markdown_plus_latex   # For relative path testing

  markdown: ^7.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  fonts:
    - family: 'Roboto Mono'
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

  uses-material-design: true

dartfmt:
  line_length: 120
