name: flutter_secure_storage
description: A Flutter plugin for securely storing sensitive data using encrypted storage.
version: 10.0.0
repository: https://github.com/mogol/flutter_secure_storage/tree/develop/flutter_secure_storage

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        default_package: flutter_secure_storage_darwin
      macos:
        default_package: flutter_secure_storage_darwin
      linux:
        default_package: flutter_secure_storage_linux
      web:
        default_package: flutter_secure_storage_web
      windows:
        default_package: flutter_secure_storage_windows

dependencies:
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # implementation constraints as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # https://github.com/flutter/flutter/issues/46264
  flutter_secure_storage_darwin: ^0.2.0
  flutter_secure_storage_linux: ^3.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.1.0
  flutter_secure_storage_windows: ^4.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: '>=6.0.0 <11.0.0'

# We need to manually declare supported platforms, because pub.dev won't find them.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
